name: Hello World Workflow

on:
  workflow_call:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    environment: Development

    steps:
      - name: Print Names
        run: |
          echo "List: ${{ vars.PRINT }}"
